version: '3'
services:
    app:
        build: .
        container_name: malik
        tty: true
        ports:
            - "80:80"
            - "443:443"
            - "3306:3306"
            - "5432:5432"
        volumes:
                - "./laravel-app:/var/www/"